services:
  mysql:
    image: mysql:8.4
    container_name: qiming-bbs-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: qiming_bbs
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - qiming_bbs_mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  qiming_bbs_mysql:
